### PR TITLE
Create labels in a loop

### PR DESCRIPTION
**Pull request by cclauss**
Create labels in a loop...  I don't think that any of these labels need a variable name.

### CODE REVIEW

**Comment by resserone13** [comment]
I made a fuction called make_link. It’s Just like your make_box. Which
would be better function or loop.?

**Comment by cclauss** [comment]
Both work...  Use whichever is easier.

I did a loop because I did not think that we needed variable names but this is not super important.

**Comment by cclauss** [comment]
You can close this PR if it is not helpful.

**Comment by resserone13** [comment]
I set up the code so that it’s being viewed side-by-side. How do I switch
it back so that the code is on top of each other instead of side-by-side.
I’m having trouble reading the 4 loop and I can’t figure out how to switch
it back to the different view

**Comment by cclauss** [comment]
When looking at the file, under the gear icon, unified/split, apply & reload.

**Comment by resserone13** [comment]
I apologize but I can’t find the gear icon

**Comment by resserone13** [comment]
I was able to look at the code by just opening the file but I still can’t figure out how to change the view or find the gear icon

**Comment by resserone13** [comment]
0E3EFEF7-7CC0-46C9-A9DB-A3CBB9B5D0A7

**Comment by cclauss** [comment]
Are you looking at the file in Pythonista or GitHub?

Screen Shot 2021-01-04 at 12 49 41

**Comment by cclauss** [comment]
The gear icon is just under `Checks` and just to the right of `Jump to...`

**Comment by resserone13** [comment]
I Finally found it. It’s so frustrating. I had to turn the phone landscape.
I’m on my iPhone 11 using Safari

**Review by resserone13 — APPROVED** [review]
This is less code and I believe will be easier to update then using the function.

**Pull request merged**
