### PR TITLE
Fix labels and images

### PR DESCRIPTION
**Pull request by cclauss**
Also, we are missing image `Level3Mask.PNG` which is mentioned on line 223,

### CODE REVIEW

**Comment by resserone13** [comment]
I’ve uploaded the image.

**Comment by resserone13** [comment]
I uploaded the image. Thanks. I added the image to the main mask page. I
will update the code.

**Comment by resserone13** [comment]
Uploaded image.

**Comment by cclauss** [comment]
Looks good!  The Face Shield image looks too large compared to other images.

**Pull request merged**
